name: helloworld
replicas: 2


image: 
  repository: anson1138/helloworld2
  tag: 1
#image: anson1138/helloworld:3

createNamespace: true
#namespace: ${infra.kubernetes.namespace}

# Service Type allow you to specify what kind of service you want.
# Possible values for ServiceType are:
# ClusterIP | NodePort | LoadBalancer | ExternalName
serviceType: NodePort

# A Service can map an incoming port to any targetPort.
# targetPort is where application is listening on inside the container.
servicePort: 80
serviceTargetPort: 80


